api_custom_config.settings_form:
  path: '/admin/config/api_custom_config/settings'
  defaults:
    _form: '\Drupal\api_custom_config\Form\SettingsForm'
    _title: 'API Custom Config (Routing)'
  requirements:
    _permission: 'administer site configuration'
